CREATE DATABASE IF NOT EXISTS imc;

USE imc;

CREATE TABLE IF NOT EXISTS registros (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    endereco VARCHAR(255) NOT NULL,
    altura FLOAT NOT NULL,
    peso FLOAT NOT NULL,
    imc FLOAT NOT NULL,
    categoria_imc VARCHAR(50) NOT NULL
);
